### ISSUE TITLE
Cannot Able to Deploy tokens on Private Node Running on Geth

### ISSUE THREAD

**Issue by sir-argupta** [vittominacori/token-generator#10]
Hi 
I was trying to deploy token on my private geth node by modifying your your this section of code, 
`goerli:{web3Provider:"HTTP://127.0.0.1:8545",etherscanLink:"https://goerli.etherscan.io",id:15230,name:"Local Test Network"}`
but I was able to genrate transaction hash & contract address but after that, I'm getting this error
 `The contract code couldn't be stored, please check your gas limit.`
My genesis.json is this:
```
{
    "config": {
        "chainId": 15230,
        "homesteadBlock": 0,
        "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0
    },
    "difficulty": "0x400",
    "gasLimit": "0x2100000",
    "alloc": {
        "BFC348d948154f9a77332B0081135527c79d8dab": 
         { "balance": "0x1337000000000000000000" }     
    }
} 

```

My Geth version is 
VERSION:
   1.10.16-stable-20356e57
Can you please help me with this..!?

**Comment by vittominacori** [comment]
This repository is for documentation.
I do not provide support for token generator as many people forked and use it to scam.
