### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by Itayfl** [vittominacori/token-generator#4]
Hi ,
Please explain the following copied from your disclaimer,
 **In addition to the Gas Fee, each time you utilize a Smart Contract to conduct a transaction via the App, you authorize us to collect a commission of an amount of BNB of the total value of that transaction** (each, a “Commission”). Commission will be publicly visible on the App confirmation page and in MetaMask confirmation popup. You acknowledge and agree that the Commission will be transferred directly to us through the Binance Smart Chain as part of your payment. We will not collect a Commission for interactions that do not involve our App.

Itay

**Comment by vittominacori** [comment]
Hello, it means that each time you deploy a smart contract using token generator you will pay a fee as declared in the generator form and in MetaMask confirmation modal. This fee is a one time on chain payment for the service. No other payments will be collected in the future or to utilize your created token. 

It could be written in a better way. I will update this as soon as possible.

**Comment by Yaselie** [comment]
Hi
The contract is executed well but is not automatically verified
What is the problem
