### ISSUE TITLE
auto verify

### ISSUE THREAD

**Issue by Yaselie** [vittominacori/token-generator#5]
Hi
The contract is executed well but is not automatically verified
What is the problem

**Comment by vittominacori** [comment]
Hello, token verification should be automatic.

Please share token address and network to check.

**Comment by Yaselie** [comment]
The tokens I made earlier not auto verified
But the new test I did is well verified
Thankful

**Comment by Yaselie** [comment]
The tokens I made earlier not auto verified
But the new test I did is well verified
Thankful
But there is a problem
Create AmazingBEP20 tokens in the bep20 network
Send some tokens from the owner wallet to another wallet
Now go to the holders section, there is no wallet

**Comment by Yaselie** [comment]
The tokens I made earlier not auto verified
But the new test I did is well verified
Thankful
bep20 network auto verified
but
eth network don't verified
