### ISSUE TITLE
lost 400 eth on failed contract deployment

### ISSUE THREAD

**Issue by danitorgec** [vittominacori/token-generator#6]
lost 400 eth on failed contract deployment, what can i do to retrive it, and how can i avoid it next time but paying minimum gas fees, i have no problem to wait

**Comment by vittominacori** [comment]
Hello, please share transaction hash to check.

Maybe you edited suggested gas limit and transaction has gone out of gas. In that case you paid only gas.

**Comment by danitorgec** [comment]
https://etherscan.io/tx/0x2093f8259034f37e26dbab4af2adda0a34402f77b9991dab1ea53568d5b96659

Transaction Hash:
0x2093f8259034f37e26dbab4af2adda0a34402f77b9991dab1ea53568d5b96659
<https://etherscan.io/tx/0x2093f8259034f37e26dbab4af2adda0a34402f77b9991dab1ea53568d5b96659>

exactly what i did, can i retrive it?

**Comment by vittominacori** [comment]
As mentioned here you must not edit the gas limit amount. 

![image](https://user-images.githubusercontent.com/8151143/145031140-839eb01d-0927-4b11-a5cf-cf68bb65d2d3.png)

So when you try to deploy a new token do not decrease the suggested value in MetaMask popup.

![image](https://user-images.githubusercontent.com/8151143/145031300-e6f1e996-b8d3-4372-ab2d-54ec2ce4b8fc.png)
