### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Klop190** [vittominacori/token-generator#7]
Salve, ho generato un token ma vedo solo un prelievo di -0.035 ETH di commissioni

**Comment by jbb-kryo** [comment]
I see no code in this repo? Is the code for the site actually included? As this does not appear to be the case?

**Comment by vittominacori** [comment]
Here it is the repo for token generator documentation website.
Smart contracts' code is verified on block explorers but the UI code is no longer available because people forked and are impersonating token generator or scamming.
