### ISSUE TITLE
Smart Contract issue For BEP20

### ISSUE THREAD

**Issue by TriumphToken** [vittominacori/token-generator#9]
Ive used on 11.02.2022 the service Vittominacori generator, after i paid 2BNB fees, for the feature Common BEP20 ive got the token in my metamask, called Triumph, smart contract address :0x8f99d8a9dA753d74008C9490a8b57438A240eF98 few days ago, browsing into BSC scan, in search box ive inserted the smart contract address of the token ive got it, and surprise!!! while ive  press Contract button said that 0x8f99d8a9dA753d74008C9490a8b57438A240eF98is asigned to a  Similar Match Source Code 
Note: This contract matches the deployed ByteCode of the Source Code for Contract [0xA6B077aba99583F8f2AA03e2eF0DF75136c7E59A](https://bscscan.com/address/0xA6B077aba99583F8f2AA03e2eF0DF75136c7E59A
![1](https://user-images.githubusercontent.com/101704422/158558814-50c71aba-e194-4f2c-9f0c-7bb4a5eed80e.PNG)
![2](https://user-images.githubusercontent.com/101704422/158558945-9c0de7e1-9aa9-4c0a-bed2-6f8ebceb1d81.PNG)
![3](https://user-images.githubusercontent.com/101704422/158558977-f1517da8-7990-407e-ba4c-5269c2f02b0a.PNG)

**Comment by vittominacori** [comment]
Hello, having similar match is not an issue as it means that your code is similar to others built on token generator.

You could try to verify your contract again by copy/paste source code in verify contract page on bscscan https://bscscan.com/verifyContract.

* Compiler: 0.8.11+commit.d7f03943.Emscripten.clang
* Optimization: Yes
* Runs (Optimizer): 200

![image](https://user-images.githubusercontent.com/8151143/158797238-eb554a40-9740-4bc8-ac5b-e0c934b7207d.png)


Note: it says it is temporary not available so please try again later with your user credentials.

**Comment by TriumphToken** [comment]
Thank U! Understood! ;)
